# Generated by Django 5.0 on 2024-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назввание')),
                ('subject', models.CharField(max_length=120, verbose_name='Тема')),
                ('plan', models.TextField(verbose_name='План урока')),
            ],
        ),
    ]
